services:
  # -----------------------------
  # PHP (Laravel)
  # -----------------------------
  laravel_eleven_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: laravel_eleven_user
        uid: 1000
    image: laravel_eleven_app_image
    container_name: laravel_eleven_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      laravel_eleven_app_mysql:
        condition: service_healthy
    networks:
      - laravel_eleven_app_network

  # -----------------------------
  # NGINX
  # -----------------------------
  laravel_eleven_webserver:
    image: nginx:alpine
    container_name: laravel_eleven_webserver_container
    restart: unless-stopped
    ports:
      - "6162:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - laravel_eleven_app
    networks:
      - laravel_eleven_app_network

  # -----------------------------
  # MySQL
  # -----------------------------
  laravel_eleven_app_mysql:
    image: mysql:8.0
    container_name: laravel_eleven_app_mysql_container
    restart: unless-stopped
    ports:
      - "3337:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_eleven_db
      MYSQL_USER: laravel_eleven_user
      MYSQL_PASSWORD: password
    volumes:
      - laravel_eleven_mysql_data:/var/lib/mysql
    networks:
      - laravel_eleven_app_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # -----------------------------
  # phpMyAdmin
  # -----------------------------
  laravel_eleven_phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: laravel_eleven_phpmyadmin_container
    restart: unless-stopped
    ports:
      - "8383:80"
    environment:
      PMA_HOST: laravel_eleven_app_mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      laravel_eleven_app_mysql:
        condition: service_healthy
    networks:
      - laravel_eleven_app_network

# -----------------------------
# NETWORK
# -----------------------------
networks:
  laravel_eleven_app_network:
    driver: bridge

# -----------------------------
# VOLUME
# -----------------------------
volumes:
  laravel_eleven_mysql_data:
    driver: local
