services:
  laravel_eleven_app:
    build:
      args:
        user: laravel_eleven_user
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: laravel_eleven_app_image
    container_name: laravel_eleven_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www
    networks:
      - laravel_eleven_app_network

  laravel_eleven_webserver:
    image: nginx:alpine
    container_name: laravel_eleven_webserver_container
    restart: unless-stopped
    ports:
      - "6162:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - laravel_eleven_app
    networks:
      - laravel_eleven_app_network

networks:
  laravel_eleven_app_network:
    driver: bridge
